In [15]:
!pip install ydata-profiling

Collecting ydata-profiling
  Downloading ydata_profiling-4.18.1-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: scipy<1.17,>=1.8 in c:\users\madanrajma\anaconda3\lib\site-packages (from ydata-profiling) (1.16.3)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in c:\users\madanrajma\anaconda3\lib\site-packages (from ydata-profiling) (2.3.3)
Collecting matplotlib<=3.10,>=3.5 (from ydata-profiling)
  Downloading matplotlib-3.10.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: pydantic<3,>=2 in c:\users\madanrajma\anaconda3\lib\site-packages (from ydata-profiling) (2.12.4)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in c:\users\madanrajma\anaconda3\lib\site-packages (from ydata-profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in c:\users\madanrajma\anaconda3\lib\site-packages (from ydata-profiling) (3.1.6)
Collecting visions<0.8.2,>=0.7.5 (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading visions-0.8.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy<2.4,>=1.22 in c:\users\madanrajma\anaconda3\lib\site-packages (from ydata-profiling) (2.3.5)
Collecting minify-html>=0.15.0 (from ydata-profiling)
  Downloading minify_html-0.18.1-cp313-cp313-win_amd64.whl.metadata (18 kB)
Collecting filetype>=1.0.0 (from ydata-profiling)
  Downloading filetype-1.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Collecting phik<0.13,>=0.12.5 (from ydata-profiling)
  Downloading phik-0.12.5-cp313-cp313-win_amd64.whl.metadata (5.6 kB)
Requirement already satisfied: requests<3,>=2.32.0 in c:\users\madanrajma\anaconda3\lib\site-packages (from ydata-profiling) (2.32.5)
Requirement already satisfied: tqdm<5,>=4.66.3 in c:\users\madanrajma\anaconda3\lib\site-packages (from ydata-profiling) (4.67.1)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in c:\users\madanrajma\anaconda3\lib\site-packages (from ydata-profiling) (0.13.2)
Collecting multimethod<2,>=1.4 (from ydata-profiling)
  Downloading multimethod-1.12-py3-none-any.whl.metadata (9.6 kB)
Requirement already satisfied: statsmodels<1,>=0.13.2 in c:\users\madanrajma\anaconda3\lib\site-packages (from ydata-profiling) (0.14.5)
Collecting typeguard<5,>=4 (from ydata-profiling)
  Downloading typeguard-4.5.1-py3-none-any.whl.metadata (3.8 kB)
Collecting imagehash==4.3.2 (from ydata-profiling)
  Downloading ImageHash-4.3.2-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting wordcloud>=1.9.4 (from ydata-profiling)
  Downloading wordcloud-1.9.6-cp313-cp313-win_amd64.whl.metadata (3.5 kB)
Collecting dacite<2,>=1.9 (from ydata-profiling)
  Downloading dacite-1.9.2-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: numba<0.63,>=0.60 in c:\users\madanrajma\anaconda3\lib\site-packages (from ydata-profiling) (0.62.1)
Requirement already satisfied: PyWavelets in c:\users\madanrajma\anaconda3\lib\site-packages (from imagehash==4.3.2->ydata-profiling) (1.9.0)
Requirement already satisfied: pillow in c:\users\madanrajma\anaconda3\lib\site-packages (from imagehash==4.3.2->ydata-profiling) (12.0.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\madanrajma\anaconda3\lib\site-packages (from jinja2<3.2,>=3.1.6->ydata-profiling) (3.0.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\madanrajma\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\madanrajma\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\madanrajma\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\madanrajma\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\madanrajma\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (25.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\madanrajma\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\madanrajma\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.46,>=0.45.0dev0 in c:\users\madanrajma\anaconda3\lib\site-packages (from numba<0.63,>=0.60->ydata-profiling) (0.45.1)
Requirement already satisfied: pytz>=2020.1 in c:\users\madanrajma\anaconda3\lib\site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\madanrajma\anaconda3\lib\site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2025.2)
Requirement already satisfied: joblib>=0.14.1 in c:\users\madanrajma\anaconda3\lib\site-packages (from phik<0.13,>=0.12.5->ydata-profiling) (1.5.2)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\madanrajma\anaconda3\lib\site-packages (from pydantic<3,>=2->ydata-profiling) (0.6.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\users\madanrajma\anaconda3\lib\site-packages (from pydantic<3,>=2->ydata-profiling) (2.41.5)
Requirement already satisfied: typing-extensions>=4.14.1 in c:\users\madanrajma\anaconda3\lib\site-packages (from pydantic<3,>=2->ydata-profiling) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\madanrajma\anaconda3\lib\site-packages (from pydantic<3,>=2->ydata-profiling) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\madanrajma\anaconda3\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\madanrajma\anaconda3\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\madanrajma\anaconda3\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\madanrajma\anaconda3\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (2025.11.12)
Requirement already satisfied: patsy>=0.5.6 in c:\users\madanrajma\anaconda3\lib\site-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.1)
Requirement already satisfied: colorama in c:\users\madanrajma\anaconda3\lib\site-packages (from tqdm<5,>=4.66.3->ydata-profiling) (0.4.6)
Requirement already satisfied: attrs>=19.3.0 in c:\users\madanrajma\anaconda3\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (25.4.0)
Requirement already satisfied: networkx>=2.4 in c:\users\madanrajma\anaconda3\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.5)
Collecting puremagic (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading puremagic-2.2.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: six>=1.5 in c:\users\madanrajma\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.17.0)
Downloading ydata_profiling-4.18.1-py2.py3-none-any.whl (400 kB)
Downloading ImageHash-4.3.2-py2.py3-none-any.whl (296 kB)
Downloading dacite-1.9.2-py3-none-any.whl (16 kB)
Downloading matplotlib-3.10.0-cp313-cp313-win_amd64.whl (8.0 MB)
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.0 MB 3.7 MB/s eta 0:00:03
   ----------- ---------------------------- 2.4/8.0 MB 7.0 MB/s eta 0:00:01
   ---------------------- ----------------- 4.5/8.0 MB 8.1 MB/s eta 0:00:01
   --------------------------------- ------ 6.8/8.0 MB 9.0 MB/s eta 0:00:01
   ---------------------------------------  7.9/8.0 MB 9.2 MB/s eta 0:00:01
   ---------------------------------------- 8.0/8.0 MB 8.1 MB/s  0:00:01
Downloading multimethod-1.12-py3-none-any.whl (10 kB)
Downloading phik-0.12.5-cp313-cp313-win_amd64.whl (678 kB)
   ---------------------------------------- 0.0/678.1 kB ? eta -:--:--
   ---------------------------------------- 678.1/678.1 kB 3.8 MB/s  0:00:00
Downloading typeguard-4.5.1-py3-none-any.whl (36 kB)
Downloading visions-0.8.1-py3-none-any.whl (105 kB)
Downloading filetype-1.2.0-py2.py3-none-any.whl (19 kB)
Downloading minify_html-0.18.1-cp313-cp313-win_amd64.whl (3.1 MB)
   ---------------------------------------- 0.0/3.1 MB ? eta -:--:--
   ----------------------- ---------------- 1.8/3.1 MB 9.3 MB/s eta 0:00:01
   ---------------------------------------- 3.1/3.1 MB 10.3 MB/s  0:00:00
Downloading wordcloud-1.9.6-cp313-cp313-win_amd64.whl (306 kB)
Downloading puremagic-2.2.0-py3-none-any.whl (71 kB)
Installing collected packages: minify-html, filetype, typeguard, puremagic, multimethod, dacite, matplotlib, imagehash, wordcloud, visions, phik, ydata-profiling

   --- ------------------------------------  1/12 [filetype]
   ------ ---------------------------------  2/12 [typeguard]
   ---------------- -----------------------  5/12 [dacite]
  Attempting uninstall: matplotlib
   ---------------- -----------------------  5/12 [dacite]
    Found existing installation: matplotlib 3.10.6
   ---------------- -----------------------  5/12 [dacite]
   -------------------- -------------------  6/12 [matplotlib]
    Uninstalling matplotlib-3.10.6:
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
      Successfully uninstalled matplotlib-3.10.6
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   ----------------------- ----------------  7/12 [imagehash]
   ------------------------------ ---------  9/12 [visions]
   ------------------------------ ---------  9/12 [visions]
   ------------------------------ ---------  9/12 [visions]
   ------------------------------ ---------  9/12 [visions]
   ------------------------------ ---------  9/12 [visions]
   ------------------------------------ --- 11/12 [ydata-profiling]
   ------------------------------------ --- 11/12 [ydata-profiling]
   ------------------------------------ --- 11/12 [ydata-profiling]
   ------------------------------------ --- 11/12 [ydata-profiling]
   ------------------------------------ --- 11/12 [ydata-profiling]
   ------------------------------------ --- 11/12 [ydata-profiling]
   ------------------------------------ --- 11/12 [ydata-profiling]
   ---------------------------------------- 12/12 [ydata-profiling]

Successfully installed dacite-1.9.2 filetype-1.2.0 imagehash-4.3.2 matplotlib-3.10.0 minify-html-0.18.1 multimethod-1.12 phik-0.12.5 puremagic-2.2.0 typeguard-4.5.1 visions-0.8.1 wordcloud-1.9.6 ydata-profiling-4.18.1

In [17]:
import pandas as pd
from ydata_profiling import ProfileReport

In [ ]:
# Load the data
df = pd.read_csv('../../01_raw/raw_renewal_calls.csv')

C:\Users\MadanRajMA\AppData\Local\Temp\ipykernel_7904\2620077442.py:2: DtypeWarning: Columns (4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,34) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('C:\\Users\\MadanRajMA\\Documents\\DS-Proj\\ds-mini-project\\data\\cleaned\\renewal_calls_cleaned.csv')

In [4]:
# Dataset Overview
df.head() # preview a sample

,call_id,call_direction,co_ref,call_date,complaint_category,customer_reaction_category,agent_renewal_pitch_category,customer_renewal_response_category,agent_response_category,membership_renewal_decision,...,agent_initiated_renewal_flag,competitor_mentioned_flag,switching_intent_flag,price_switching_flag,pct_price_increase_flag,monetary_price_increase_flag,customer_asked_justification_flag,discount_offered_flag,renewal_confirmed_flag,customer_response_score
0,5.950000e+11,Outbound,UB0899,2025-01-29,NaN,Not Mentioned,Discussion / Introduction / Inquiry,Discount and Offer,Discount and Offer,No,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
1,5.970000e+11,Outbound,HN5141,2025-02-26,NaN,NaN,Price and Cost,Agreement,Customer Communication,No,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
2,5.950000e+11,Outbound,BP5009,2025-01-24,NaN,NaN,Expiration / Due,Agreement,Accreditation and Certification,No,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
3,6.520000e+11,Outbound,XP8119,2025-06-09,NaN,NaN,Auto / Automatic,Agreement,Accreditation and Certification,No,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
4,5.370000e+11,Outbound,ZL7978,2024-08-20,NaN,NaN,NaN,NaN,NaN,No,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN

In [5]:
df.shape

(102593, 52)

In [6]:
df.dtypes

call_id                                  float64
call_direction                            object
co_ref                                    object
call_date                                 object
complaint_category                        object
customer_reaction_category                object
agent_renewal_pitch_category              object
customer_renewal_response_category        object
agent_response_category                   object
membership_renewal_decision               object
serious_complaint                         object
other_complaint                           object
discussion_on_price_increase              object
renewal_impact_due_to_price_increase      object
discount_or_waiver_requested              object
call_reschedule_request                   object
agent_flagged_membership_status_alert     object
agent_renewal_initiation                  object
explicit_competitor_mention               object
explicit_switching_intent                 object
mentioned_competitors                     object
price_switching_mentioned                 object
competitor_value_comparison               object
competitor_benefits_mentioned             object
topic_introduced_by                       object
percentage_price_increase_mentioned       object
monetary_price_increase_mentioned         object
price_range_mentioned                     object
customer_asked_for_justification          object
customer_response                         object
desire_to_cancel                          object
discount_offered                          object
call_number                                int64
is_analysed                                int64
desire_to_cancel_clean                    object
serious_complaint_flag                   float64
other_complaint_flag                     float64
price_discussed_flag                     float64
price_impact_renewal_flag                float64
discount_requested_flag                  float64
call_reschedule_flag                     float64
membership_alert_flag                    float64
agent_initiated_renewal_flag             float64
competitor_mentioned_flag                float64
switching_intent_flag                    float64
price_switching_flag                     float64
pct_price_increase_flag                  float64
monetary_price_increase_flag             float64
customer_asked_justification_flag        float64
discount_offered_flag                    float64
renewal_confirmed_flag                   float64
customer_response_score                  float64
dtype: object

In [9]:
df[df.duplicated()]

,call_id,call_direction,co_ref,call_date,complaint_category,customer_reaction_category,agent_renewal_pitch_category,customer_renewal_response_category,agent_response_category,membership_renewal_decision,...,agent_initiated_renewal_flag,competitor_mentioned_flag,switching_intent_flag,price_switching_flag,pct_price_increase_flag,monetary_price_increase_flag,customer_asked_justification_flag,discount_offered_flag,renewal_confirmed_flag,customer_response_score
38527,5.950000e+11,Inbound,CI1981,2025-01-22,NaN,NaN,Annual,Agreement,Payment,No,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44366,5.370000e+11,Outbound,ZL7978,2024-08-21,NaN,NaN,Cancellation / Termination / Non-Renewal / Clo...,Agreement,Payment,No,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [10]:
df.isna().sum()

call_id                                      0
call_direction                               0
co_ref                                       0
call_date                                    0
complaint_category                       90394
customer_reaction_category               86915
agent_renewal_pitch_category             65587
customer_renewal_response_category       65269
agent_response_category                  65484
membership_renewal_decision              45872
serious_complaint                        47544
other_complaint                          47545
discussion_on_price_increase             44739
renewal_impact_due_to_price_increase     44758
discount_or_waiver_requested             44758
call_reschedule_request                  44440
agent_flagged_membership_status_alert    44440
agent_renewal_initiation                 44440
explicit_competitor_mention              44358
explicit_switching_intent                44358
mentioned_competitors                    44357
price_switching_mentioned                44379
competitor_value_comparison              44377
competitor_benefits_mentioned            45866
topic_introduced_by                      44342
percentage_price_increase_mentioned      44342
monetary_price_increase_mentioned        44342
price_range_mentioned                    44342
customer_asked_for_justification         44342
customer_response                        44342
desire_to_cancel                         44345
discount_offered                         44342
call_number                                  0
is_analysed                                  0
desire_to_cancel_clean                   44345
serious_complaint_flag                   47544
other_complaint_flag                     47545
price_discussed_flag                     44739
price_impact_renewal_flag                44758
discount_requested_flag                  44758
call_reschedule_flag                     44440
membership_alert_flag                    44440
agent_initiated_renewal_flag             44440
competitor_mentioned_flag                44358
switching_intent_flag                    44358
price_switching_flag                     44379
pct_price_increase_flag                  44342
monetary_price_increase_flag             44342
customer_asked_justification_flag        44342
discount_offered_flag                    44342
renewal_confirmed_flag                   45872
customer_response_score                  58954
dtype: int64

In [11]:
df.isna().sum().sum() # number of missing cells
round(df.isna().sum().sum() / df.size * 100, 1) # percentage of missing cells

np.float64(41.7)

In [13]:
df.describe(include='object')

,call_direction,co_ref,call_date,complaint_category,customer_reaction_category,agent_renewal_pitch_category,customer_renewal_response_category,agent_response_category,membership_renewal_decision,serious_complaint,...,competitor_benefits_mentioned,topic_introduced_by,percentage_price_increase_mentioned,monetary_price_increase_mentioned,price_range_mentioned,customer_asked_for_justification,customer_response,desire_to_cancel,discount_offered,desire_to_cancel_clean
count,102593,102593,102593,12199,15678,37006,37324,37109,56721,55049,...,56727,58251,58251,58251,58251,58251,58251,58248,58251,58248
unique,2,25782,467,22,13,18,20,20,3,3,...,201,3,3,3,2139,3,4,294,3,3
top,Outbound,AD1657,2025-01-13,Price Increase / Rise and Value,Not Mentioned,Auto / Automatic,Agreement,Payment,No,No,...,Not Applicable,Not Discussed,No,No,Not Discussed,No,Neutral,Renewed,No,renew
freq,86824,161,422,2181,7526,9920,7830,7348,52305,54647,...,42098,43000,57420,56013,55403,54040,39562,29128,53860,29705

In [ ]:
profile = ProfileReport(df,title="Renewal Calls")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████████████████████████████████████████████████████████████████████████████| 52/52 [00:14<00:00,  3.54it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

In [20]:
profile.to_file("renewal_calls.html")

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]